version: '3'

env:
  ENV: testing

tasks:
  default:
    dotenv: ['.env', '{{.ENV}}/.env', '{{.HOME}}/.env']
    env:
      KEYNAME: DIFFERENT_VALUE
    cmds:
      - echo "Using $KEYNAME and endpoint $ENDPOINT"